# -*- mode: ruby -*-
# vim: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/22.04"
  config.ssh.host = "127.0.0.1"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end


  config.vm.provision "shell", inline: <<-SHELL
    sysctl -w net.ipv4.ip_forward=1
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4
    apt-get update -y && apt-get install -y traceroute
  SHELL

  MACHINES = {
    "router1" => [
      {ip: "192.168.56.10", mask: "255.255.255.0"},                # management
      {ip: "192.168.10.1",  mask: "255.255.255.0", intnet: "net1"},
      {ip: "10.0.10.1",     mask: "255.255.255.252", intnet: "r1-r2"},
      {ip: "10.0.12.2",     mask: "255.255.255.252", intnet: "r1-r3"}
    ],
    "router2" => [
      {ip: "192.168.56.11", mask: "255.255.255.0"},
      {ip: "192.168.20.1",  mask: "255.255.255.0", intnet: "net2"},
      {ip: "10.0.10.2",     mask: "255.255.255.252", intnet: "r1-r2"},
      {ip: "10.0.11.2",     mask: "255.255.255.252", intnet: "r2-r3"}
    ],
    "router3" => [
      {ip: "192.168.56.12", mask: "255.255.255.0"},
      {ip: "192.168.30.1",  mask: "255.255.255.0", intnet: "net3"},
      {ip: "10.0.11.1",     mask: "255.255.255.252", intnet: "r2-r3"},
      {ip: "10.0.12.1",     mask: "255.255.255.252", intnet: "r1-r3"}
    ]
  }

  MACHINES.each do |name, interfaces|
    config.vm.define name do |node|
      node.vm.hostname = name
      interfaces.each do |iface|
        if iface.key?(:intnet)
          node.vm.network "private_network",
                          ip: iface[:ip],
                          netmask: iface[:mask],
                          virtualbox__intnet: iface[:intnet]
        else
          node.vm.network "private_network",
                          ip: iface[:ip],
                          netmask: iface[:mask]
        end
      end
    end
  end

  config.vm.define "router3" do |node|
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision.yml"
      ansible.inventory_path = "ansible/inventory.ini"
      ansible.host_key_checking = "false"
      ansible.limit = "all"
    end
  end
end