---
- name: Prepare Infrastructure
  hosts: all
  become: true
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Ensure SELinux is disabled in config
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'

    - name: Stop and disable Firewalld (to avoid issues in Vagrant)
      service:
        name: firewalld
        state: stopped
        enabled: false
      ignore_errors: true  # Если пакета нет вообще, плейбук не упадет

- name: Configure Central Log Server
  hosts: log
  become: true
  tasks:
    - name: Install rsyslog
      dnf:
        name: rsyslog
        state: present

    - name: Enable UDP and TCP reception in rsyslog.conf
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^[#\s]*module\(load="imudp"\)', line: 'module(load="imudp")' }
        - { regexp: '^[#\s]*input\(type="imudp" port="514"\)', line: 'input(type="imudp" port="514")' }
        - { regexp: '^[#\s]*module\(load="imtcp"\)', line: 'module(load="imtcp")' }
        - { regexp: '^[#\s]*input\(type="imtcp" port="514"\)', line: 'input(type="imtcp" port="514")' }
      notify: restart rsyslog

    - name: Add remote logging rules to the end of rsyslog.conf
      blockinfile:
        path: /etc/rsyslog.conf
        insertafter: EOF
        block: |
          # Правила приёма сообщений от хостов
          $template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
          *.* ?RemoteLogs
          & ~
      notify: restart rsyslog

    - name: Ensure rsyslog is started
      service:
        name: rsyslog
        state: started
        enabled: true

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted

- name: Configure Web Server
  hosts: web
  become: true
  vars:
    log_server_ip: "192.168.56.15"
  tasks:
    - name: Install Nginx, rsyslog and auditd
      dnf:
        name: [nginx, rsyslog, audit, audispd-plugins]
        state: present

    - name: Configure Nginx logging in nginx.conf
      blockinfile:
        path: /etc/nginx/nginx.conf
        insertafter: 'access_log  /var/log/nginx/access.log  main;'
        block: |
          # Настройка удаленного логирования Access
          access_log syslog:server={{ log_server_ip }}:514,tag=nginx_access combined;

          # Настройка Error логов: локально (только crit+) и удаленно (все по умолчанию)
          error_log /var/log/nginx/error.log crit;
          error_log syslog:server={{ log_server_ip }}:514,tag=nginx_error;
      notify: check and restart nginx

    - name: Configure rsyslog for Audit and Critical logs
      copy:
        dest: /etc/rsyslog.d/forward.conf
        content: |
          # Критичные логи системы локально и удаленно
          *.crit  /var/log/critical.log
          *.crit  @{{ log_server_ip }}:514

          # Пересылка аудита (чтение файла и отправка)
          module(load="imfile")
          input(type="imfile"
                File="/var/log/audit/audit.log"
                Tag="auditd"
                Severity="info"
                Facility="local6")
          local6.* @{{ log_server_ip }}:514
      notify: restart rsyslog

    - name: Set auditd rules for Nginx configs
      copy:
        dest: /etc/audit/rules.d/nginx.rules
        content: |
          -w /etc/nginx/nginx.conf -p wa -k nginx_conf
          -w /etc/nginx/conf.d/ -p wa -k nginx_conf
      notify: restart auditd

    - name: Start services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: [nginx, rsyslog, auditd]

  handlers:
    - name: check and restart nginx
      shell: "nginx -t && systemctl restart nginx"

    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted

    - name: restart auditd
      shell: "service auditd restart || systemctl restart auditd || augenrules --load"
      ignore_errors: true
...
