---
- name: Install bind9
  apt:
    name: bind9
    state: present

- name: Configure named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Configure named.conf.local (zones)
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9

- name: Ensure bind9 is running
  systemd:
    name: named
    enabled: yes
    state: started