# -*- mode: ruby -*-
# vi: set ft=ruby :1
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
my_network = "Realtek Gaming 2.5GbE Family Controller"
Vagrant.configure("2") do |config|
  config.ssh.host = "127.0.0.1"  
  config.vm.box = "ubuntu/22.04"
  config.vbguest.auto_update = false
  config.vm.boot_timeout = 900
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.linked_clone = false 
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]	
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.define "lb1" do |node|
    node.vm.hostname = "lb1"
    node.vm.network "public_network", ip: "192.168.77.11", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "lb2" do |node|
    node.vm.hostname = "lb2"
    node.vm.network "public_network", ip: "192.168.77.12", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "db1" do |node|
    node.vm.hostname = "db1"
    node.vm.network "public_network", ip: "192.168.77.21", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "db2" do |node|
    node.vm.hostname = "db2"
    node.vm.network "public_network", ip: "192.168.77.22", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "db3" do |node|
    node.vm.hostname = "db3"
    node.vm.network "public_network", ip: "192.168.77.23", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "pdns1" do |node|
    node.vm.hostname = "pdns1"
    node.vm.network "public_network", ip: "192.168.77.31", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "pdns2" do |node|
    node.vm.hostname = "pdns2"
    node.vm.network "public_network", ip: "192.168.77.32", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "split-dns" do |node|
    node.vm.hostname = "split-dns"
    node.vm.network "public_network", ip: "192.168.77.40", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "mon" do |node|
    node.vm.hostname = "mon"
    node.vm.network "public_network", ip: "192.168.77.50", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  config.vm.define "bkp" do |node|
    node.vm.hostname = "bkp"
    node.vm.network "public_network", ip: "192.168.77.60", bridge: my_network
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision.yml"
      ansible.inventory_path = "ansible/hosts"
      ansible.vault_password_file = "~/.ansible_vault_pass"
      ansible.limit = "all"
      ansible.compatibility_mode = "2.0"
      ansible.raw_arguments = ["--timeout=60"]
    end
  end

end