Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  
  # Исправление для WSL2: принудительно работаем через localhost
  config.ssh.host = "127.0.0.1"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Установка зависимостей на все машины
  config.vm.provision "shell", inline: "dnf install -y python3 nano"

  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "log" do |log|
    log.vm.hostname = "log"
    log.vm.network "private_network", ip: "192.168.56.15"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.compatibility_mode = "2.0"
    # Vagrant сам распределит хосты по группам из имен define
    ansible.groups = {
      "web" => ["web"],
      "log" => ["log"]
    }
  end
end
