---
- name: restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart php8.1-fpm 
  systemd:
    name: php8.1-fpm
    state: restarted