---
  - name: Install postgresql-server 14
    apt:
      name:
          - postgresql
          - postgresql-contrib
      state: present
      update_cache: true

  - name: Enable and start PostgreSQL service
    service:
      name: postgresql
      state: started
      enabled: true
